### PR TITLE
Help page revised

### PR DESCRIPTION
**Pull request by Tristan816la**
commit
Make the help page look like the design.

Two things that worth noticing
1) Arrow-back now is gray, since I don't think we have a white arrow back in the public folder
2) Send feedback will direct user to DevX main page.

### CODE REVIEW

**Comment by thilan-tran** [comment]
You can actually easily change the color of an svg icon by modifying the `fill` value since it is actually just an html object under the surface.

 So you can make a white arrow by copying over `arrow-left.svg` to a `white-arrow-left.svg` file and updating the `fill="#777"` to `fill="#fff"`.

**Comment by alexlongerbeam** [comment]
Looks good to me! However @thilan-tran would you mind telling Tristan the best way to find a white back arrow? Is there a certain icon site you usually use? @Tristan816la this will be a good experience for you to learn about bringing in new assets

**Comment by thilan-tran** [comment]
Yeah, I normally use [Ionicons](https://ionicons.com/) which has really well done icons, but I commented above how to actually modify the other svg icon file to make it white, which is surprisingly easy to do.

**Comment by Tristan816la** [comment]
OK. Just change the color to white by using the method you said. Thanks!

**Review by alexlongerbeam — APPROVED** [review]
Looks good!

**Pull request merged**
