### PR TITLE
Initial onboarding

### PR DESCRIPTION
**Pull request by thilan-tran**
Implemented initial onboarding functionality.

TODO:
* fix UI with buttons
* fix UI with background
* remove some placeholder buttons

Preview:
onboarding_prototype

### CODE REVIEW

**Review by alexlongerbeam — APPROVED** [review]
Code looks good. Let's make sure @claireg22  is on board, and also just keep us updated on the plans for what is to be changed.

**Review by claireg22 — APPROVED** [review]
Looks really good! But is there any way it can stick closer to the original figma design? Just for consistency!

**Comment by thilan-tran** [comment]
Yeah of course, I'm still going to change the next button style, the background, and the time dropdown so it fits better on one line. But is there something specifically about the text or other dropdowns that you want me to update?

**Comment by claireg22** [comment]
Ok cool! The dropdowns look good - maybe change the font to Roboto to make it look more like Google

**Pull request merged**
